
[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "klarity"
version = "0.1.0"
description = "Uncertainty estimation for open-source generative models"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.0.0",
    "pydantic>=2.0.0",
    "scikit-learn>=1.0.0",
    "sentence-transformers>=2.0.0",
    "numpy>=1.20.0"
]